
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 38;
  public static final int READLINE = 26;
  public static final int PLUS_ASSIGN = 43;
  public static final int NOT_EQUAL = 48;
  public static final int TIME = 40;
  public static final int DOUBLE = 10;
  public static final int GREATER = 53;
  public static final int PRIVATE = 23;
  public static final int CONTINUE = 8;
  public static final int T_DOUBLELITERAL = 36;
  public static final int INT = 16;
  public static final int LESS = 51;
  public static final int MINUS = 44;
  public static final int FOR = 13;
  public static final int DEFINE = 9;
  public static final int SEMICOLON = 58;
  public static final int AND = 49;
  public static final int NOT = 47;
  public static final int READINTEGER = 25;
  public static final int OR = 50;
  public static final int COMMA = 57;
  public static final int BOOL = 4;
  public static final int CLASS = 7;
  public static final int T_INTLITERAL = 35;
  public static final int LESS_EQUAL = 52;
  public static final int NEWARRAY = 20;
  public static final int PLUS = 42;
  public static final int ASSIGN = 46;
  public static final int IF = 14;
  public static final int THIS = 29;
  public static final int DOT = 56;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int EQUAL = 55;
  public static final int GREATER_EQUAL = 54;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MODE = 37;
  public static final int CLOSEBRACKET = 64;
  public static final int T_STRINGLITERAL = 33;
  public static final int LINE = 3;
  public static final int NULL = 21;
  public static final int BREAK = 5;
  public static final int CLOSECURLY = 62;
  public static final int VOID = 30;
  public static final int DTOI = 11;
  public static final int IMPORT = 15;
  public static final int OPENCURLY = 61;
  public static final int ELSE = 12;
  public static final int OPENBRACKET = 63;
  public static final int FUNC = 2;
  public static final int TIME_ASSIGN = 41;
  public static final int ITOD = 18;
  public static final int ITOB = 17;
  public static final int WHILE = 31;
  public static final int CLOSEBRACE = 60;
  public static final int DIVIDE_ASSIGN = 39;
  public static final int OP_CL_BRACKET = 65;
  public static final int PUBLIC = 24;
  public static final int BTOI = 6;
  public static final int OPENBRACE = 59;
  public static final int STRING = 28;
  public static final int T_BOOLEANLITERAL = 34;
  public static final int T_ID = 32;
  public static final int MINUS_ASSIGN = 45;
  public static final int PRINT = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNC",
  "LINE",
  "BOOL",
  "BREAK",
  "BTOI",
  "CLASS",
  "CONTINUE",
  "DEFINE",
  "DOUBLE",
  "DTOI",
  "ELSE",
  "FOR",
  "IF",
  "IMPORT",
  "INT",
  "ITOB",
  "ITOD",
  "NEW",
  "NEWARRAY",
  "NULL",
  "PRINT",
  "PRIVATE",
  "PUBLIC",
  "READINTEGER",
  "READLINE",
  "RETURN",
  "STRING",
  "THIS",
  "VOID",
  "WHILE",
  "T_ID",
  "T_STRINGLITERAL",
  "T_BOOLEANLITERAL",
  "T_INTLITERAL",
  "T_DOUBLELITERAL",
  "MODE",
  "DIVIDE",
  "DIVIDE_ASSIGN",
  "TIME",
  "TIME_ASSIGN",
  "PLUS",
  "PLUS_ASSIGN",
  "MINUS",
  "MINUS_ASSIGN",
  "ASSIGN",
  "NOT",
  "NOT_EQUAL",
  "AND",
  "OR",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "EQUAL",
  "DOT",
  "COMMA",
  "SEMICOLON",
  "OPENBRACE",
  "CLOSEBRACE",
  "OPENCURLY",
  "CLOSECURLY",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "OP_CL_BRACKET"
  };
}

